"""
Strategy Engine - Automated Trading Logic
============================================
Signal generation, ATM options analysis, entry/exit logic,
multi-timeframe analysis for fully automated execution.
"""

import time
import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
from collections import deque

logger = logging.getLogger(__name__)


class SignalType(Enum):
    BUY_CE = "BUY_CE"
    BUY_PE = "BUY_PE"
    EXIT_CE = "EXIT_CE"
    EXIT_PE = "EXIT_PE"
    NO_SIGNAL = "NO_SIGNAL"


class SignalStrength(Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"



@dataclass
class Signal:
    """Trading signal generated by strategy."""
    signal_id: str = ""
    signal_type: SignalType = SignalType.NO_SIGNAL
    strength: SignalStrength = SignalStrength.WEAK
    symbol: str = ""
    instrument: str = ""  # NIFTY, BANKNIFTY
    strike: float = 0.0
    option_type: str = ""  # CE, PE
    entry_price: float = 0.0
    stop_loss: float = 0.0
    target_1: float = 0.0
    target_2: float = 0.0
    target_3: float = 0.0
    quantity: int = 0
    confidence: float = 0.0  # 0-100
    reason: str = ""
    timeframe: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Contributing factors
    factors: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyState:
    """Current state of the strategy."""
    active: bool = False
    in_position: bool = False
    current_signal: Optional[Signal] = None
    last_signal_time: Optional[datetime] = None
    signals_generated: int = 0
    trades_taken: int = 0
    win_rate: float = 0.0
    mode: str = "semi_auto"  # full_auto, semi_auto, manual



class StrategyEngine:
    """
    Core strategy engine for ATM options trading.
    
    Strategy Logic:
    1. Monitor index charts (NIFTY, BANKNIFTY)
    2. Analyze market depth, OI changes, volume
    3. Generate signals for ATM CE/PE based on:
       - OI change analysis (multi-timeframe)
       - IV levels and changes
       - Market breadth and trend
       - VWAP positioning
       - Volume spikes
       - Smart money flow
    4. Execute with proper risk management
    
    Modes:
    - full_auto: Execute signals automatically
    - semi_auto: Generate signals, require button confirmation
    - manual: Display analysis, no auto-signals
    """

    def __init__(self, market_data, risk_manager, money_manager, config: Dict):
        self.market_data = market_data
        self.risk_manager = risk_manager
        self.money_manager = money_manager
        self.config = config
        
        # Strategy state
        self.state = StrategyState()
        self.state.mode = config.get("automation", {}).get("mode", "semi_auto")
        
        # Signal parameters
        self.signal_config = config.get("signals", {})
        self.atm_config = config.get("atm_selection", {})
        
        # Signal history
        self.signal_history: List[Signal] = []
        self._signal_callbacks: List = []
        
        # Multi-timeframe analysis
        self._tf_scores: Dict[str, float] = {}
        
        # Signal cooldown
        self._last_signal_time: Optional[datetime] = None
        self._min_signal_gap = 60  # seconds between signals
        
        # Trade Quality Filter (Golden Egg Detector)
        from core.trade_quality_filter import TradeQualityFilter
        self.quality_filter = TradeQualityFilter(config)
        
        # Quality statistics
        self.signals_blocked = 0
        self.golden_eggs_found = 0
        self.spoiled_eggs_avoided = 0
        
        logger.info("StrategyEngine initialized | Mode: %s | Quality Filter: ACTIVE", self.state.mode)

    # =========================================================================
    # SIGNAL GENERATION
    # =========================================================================

    def analyze_market(self, instrument: str = "NIFTY") -> Signal:
        """
        Main analysis function - evaluates all factors, applies quality filter,
        and generates signal ONLY if it passes the golden egg test.
        
        Flow:
        1. Calculate 6 factor scores
        2. Generate composite score
        3. If composite exceeds threshold → candidate signal
        4. Run through Trade Quality Filter (10 checks)
        5. Only pass signals graded B or above
        6. Adjust position size based on grade (A+ = 1.5x, C = 0.5x)
        
        Returns Signal with confidence level (or NO_SIGNAL if blocked).
        """
        # Check cooldown
        if self._last_signal_time:
            elapsed = (datetime.now() - self._last_signal_time).total_seconds()
            if elapsed < self._min_signal_gap:
                return Signal(signal_type=SignalType.NO_SIGNAL, reason="Cooldown active")
        
        # Calculate individual scores
        oi_score = self._analyze_oi(instrument)
        iv_score = self._analyze_iv(instrument)
        trend_score = self._analyze_trend()
        vwap_score = self._analyze_vwap(instrument)
        volume_score = self._analyze_volume(instrument)
        flow_score = self._analyze_smart_flow(instrument)
        
        # Weighted composite score (-100 to +100)
        weights = {
            "oi": 0.25,
            "iv": 0.10,
            "trend": 0.20,
            "vwap": 0.15,
            "volume": 0.15,
            "flow": 0.15,
        }
        
        composite = (
            oi_score * weights["oi"] +
            iv_score * weights["iv"] +
            trend_score * weights["trend"] +
            vwap_score * weights["vwap"] +
            volume_score * weights["volume"] +
            flow_score * weights["flow"]
        )
        
        factors = {
            "oi_score": oi_score,
            "iv_score": iv_score,
            "trend_score": trend_score,
            "vwap_score": vwap_score,
            "volume_score": volume_score,
            "flow_score": flow_score,
            "composite": composite,
        }
        
        # Generate candidate signal based on composite
        signal = self._generate_signal(instrument, composite, factors)
        
        # If no signal generated (score too weak), return immediately
        if signal.signal_type == SignalType.NO_SIGNAL:
            return signal
        
        # ═══════════════════════════════════════════════════════════════════
        # QUALITY FILTER GATE — This is where bad trades get blocked
        # ═══════════════════════════════════════════════════════════════════
        quality = self.quality_filter.assess_trade(
            signal_data={"factors": factors, "composite": composite},
            market_data=self.market_data,
            instrument=instrument,
        )
        
        # Decision: Take or reject?
        take_trade, reason, size_multiplier = self.quality_filter.should_take_trade(
            quality, mode=self.state.mode
        )
        
        if not take_trade:
            # BLOCKED — Spoiled egg detected
            self.signals_blocked += 1
            self.spoiled_eggs_avoided += 1
            logger.info(
                "SIGNAL BLOCKED by Quality Filter [%s]: %s | "
                "Composite=%.1f but Quality=%d/100 | Reasons: %s",
                quality.grade, instrument, composite,
                quality.total_score, "; ".join(quality.rejection_reasons[:2])
            )
            return Signal(
                signal_type=SignalType.NO_SIGNAL,
                confidence=abs(composite),
                reason=f"Quality Filter BLOCKED [{quality.grade}]: {reason}",
                factors=factors,
            )
        
        # PASSED — Golden egg confirmed!
        if quality.is_golden:
            self.golden_eggs_found += 1
        
        # Adjust signal with quality info
        signal.confidence = min(quality.total_score, 100)
        signal.reason = (
            f"{signal.reason} | Quality: {quality.grade} ({quality.total_score}/100) "
            f"| Size: {size_multiplier}x"
        )
        
        # Store size multiplier for execution
        signal.factors["quality_grade"] = quality.grade
        signal.factors["quality_score"] = quality.total_score
        signal.factors["size_multiplier"] = size_multiplier
        signal.factors["quality_factors"] = quality.quality_factors
        
        # Update state
        self._last_signal_time = datetime.now()
        self.state.signals_generated += 1
        self.signal_history.append(signal)
        
        logger.info(
            "GOLDEN EGG CONFIRMED [%s] %s %s | Composite=%.1f | "
            "Quality=%d/100 | Size=%.1fx | Factors aligned: %s",
            quality.grade, signal.signal_type.value, instrument,
            composite, quality.total_score, size_multiplier,
            quality.quality_factors
        )
        
        self._notify_signal(signal)
        return signal



    def _generate_signal(
        self, instrument: str, composite: float, factors: Dict
    ) -> Signal:
        """Generate trading signal from composite score."""
        # Thresholds for signal generation (raised for quality)
        strong_threshold = 60
        moderate_threshold = 45
        weak_threshold = 35  # Raised from 25 to reject weak signals early
        
        abs_score = abs(composite)
        
        if abs_score < weak_threshold:
            return Signal(
                signal_type=SignalType.NO_SIGNAL,
                confidence=abs_score,
                reason=f"Score too weak: {composite:.1f}",
                factors=factors,
            )
        
        # Determine direction
        if composite > 0:
            signal_type = SignalType.BUY_CE
            option_type = "CE"
        else:
            signal_type = SignalType.BUY_PE
            option_type = "PE"
        
        # Determine strength
        if abs_score >= strong_threshold:
            strength = SignalStrength.VERY_STRONG
        elif abs_score >= moderate_threshold:
            strength = SignalStrength.STRONG
        elif abs_score >= weak_threshold:
            strength = SignalStrength.MODERATE
        else:
            strength = SignalStrength.WEAK
        
        # Get ATM strike
        atm_strike = self.market_data.get_atm_strike(instrument)
        
        # Build signal
        signal = Signal(
            signal_id=f"SIG_{int(time.time())}_{instrument}",
            signal_type=signal_type,
            strength=strength,
            symbol=instrument,
            instrument=instrument,
            strike=atm_strike,
            option_type=option_type,
            confidence=min(abs_score, 100),
            reason=self._build_reason(factors, signal_type),
            timeframe="multi",
            factors=factors,
        )
        
        # Calculate entry/exit levels
        self._set_trade_levels(signal)
        
        return signal

    def _set_trade_levels(self, signal: Signal) -> None:
        """Set entry price, stop loss, and targets for signal."""
        # Get current option price (would come from market data)
        chain = self.market_data.option_chains.get(signal.instrument, [])
        
        for opt in chain:
            if opt.strike == signal.strike:
                if signal.option_type == "CE":
                    signal.entry_price = opt.ce_ltp
                else:
                    signal.entry_price = opt.pe_ltp
                break
        
        if signal.entry_price > 0:
            # Stop loss at 30% of premium
            signal.stop_loss = round(signal.entry_price * 0.70, 2)
            # Targets
            signal.target_1 = round(signal.entry_price * 1.20, 2)
            signal.target_2 = round(signal.entry_price * 1.40, 2)
            signal.target_3 = round(signal.entry_price * 1.60, 2)

    # =========================================================================
    # ANALYSIS COMPONENTS
    # =========================================================================

    def _analyze_oi(self, instrument: str) -> float:
        """
        Analyze Open Interest patterns.
        Returns score from -100 (bearish) to +100 (bullish).
        
        Logic:
        - CE OI increase = Resistance being written = Bearish
        - PE OI increase = Support being written = Bullish
        - CE OI decrease = Resistance breaking = Bullish
        - PE OI decrease = Support breaking = Bearish
        """
        threshold = self.signal_config.get("oi_change_threshold", 5.0)
        
        # Get multi-timeframe OI changes
        atm = self.market_data.get_atm_strike(instrument)
        ce_key = f"{instrument}_{atm}_CE"
        pe_key = f"{instrument}_{atm}_PE"
        
        ce_change_5m = self.market_data.get_oi_change(ce_key, 5)
        pe_change_5m = self.market_data.get_oi_change(pe_key, 5)
        ce_change_15m = self.market_data.get_oi_change(ce_key, 15)
        pe_change_15m = self.market_data.get_oi_change(pe_key, 15)
        
        # Score calculation
        score = 0.0
        
        # PE buildup = Bullish (puts being written = support)
        if pe_change_5m > 0:
            score += min(30, pe_change_5m / 100)
        if pe_change_15m > 0:
            score += min(20, pe_change_15m / 200)
        
        # CE buildup = Bearish (calls being written = resistance)
        if ce_change_5m > 0:
            score -= min(30, ce_change_5m / 100)
        if ce_change_15m > 0:
            score -= min(20, ce_change_15m / 200)
        
        # OI unwinding signals
        if ce_change_5m < 0:  # CE unwinding = Bullish
            score += min(15, abs(ce_change_5m) / 200)
        if pe_change_5m < 0:  # PE unwinding = Bearish
            score -= min(15, abs(pe_change_5m) / 200)
        
        # PCR factor
        pcr = self.market_data.get_pcr(instrument)
        if pcr > 1.2:
            score += 10  # High PCR = Bullish
        elif pcr < 0.8:
            score -= 10  # Low PCR = Bearish
        
        return max(-100, min(100, score))

    def _analyze_iv(self, instrument: str) -> float:
        """Analyze Implied Volatility levels and direction."""
        chain = self.market_data.option_chains.get(instrument, [])
        if not chain:
            return 0.0
        
        # Average IV from ATM options
        atm = self.market_data.get_atm_strike(instrument)
        atm_options = [o for o in chain if abs(o.strike - atm) <= 100]
        
        if not atm_options:
            return 0.0
        
        avg_ce_iv = sum(o.ce_iv for o in atm_options) / len(atm_options)
        avg_pe_iv = sum(o.pe_iv for o in atm_options) / len(atm_options)
        
        iv_high = self.signal_config.get("iv_threshold_high", 20.0)
        iv_low = self.signal_config.get("iv_threshold_low", 12.0)
        
        score = 0.0
        avg_iv = (avg_ce_iv + avg_pe_iv) / 2
        
        # High IV = Caution (reduce confidence)
        if avg_iv > iv_high:
            score = -20  # High volatility, risky
        elif avg_iv < iv_low:
            score = 20  # Low volatility, breakout possible
        
        # IV skew (PE IV > CE IV = Market fearful = potential bounce)
        if avg_pe_iv > avg_ce_iv * 1.1:
            score += 10
        elif avg_ce_iv > avg_pe_iv * 1.1:
            score -= 10
        
        return max(-100, min(100, score))

    def _analyze_trend(self) -> float:
        """Analyze market breadth and trend strength."""
        return self.market_data.get_trend_strength_score()

    def _analyze_vwap(self, instrument: str) -> float:
        """Analyze price position relative to VWAP."""
        vwap_data = self.market_data.get_vwap(instrument)
        
        score = 0.0
        if vwap_data.price_vs_vwap == "ABOVE":
            score = 30  # Bullish - price above VWAP
        elif vwap_data.price_vs_vwap == "BELOW":
            score = -30  # Bearish - price below VWAP
        
        # Deviation from VWAP
        ltp = self.market_data.get_index_ltp(instrument)
        if ltp > 0 and vwap_data.vwap > 0:
            dev_pct = abs(ltp - vwap_data.vwap) / vwap_data.vwap * 100
            vwap_threshold = self.signal_config.get("vwap_deviation_percent", 0.5)
            
            if dev_pct > vwap_threshold:
                # Extended from VWAP - mean reversion potential
                if ltp > vwap_data.vwap:
                    score -= 10  # Potential pullback
                else:
                    score += 10  # Potential bounce
        
        return max(-100, min(100, score))

    def _analyze_volume(self, instrument: str) -> float:
        """Analyze volume patterns for confirmation."""
        multiplier = self.signal_config.get("volume_spike_multiplier", 2.0)
        
        # Simple volume analysis from tick buffer
        ticks = self.market_data._tick_buffer.get(instrument, deque())
        if len(ticks) < 20:
            return 0.0
        
        recent = list(ticks)[-10:]
        older = list(ticks)[-20:-10]
        
        recent_vol = sum(int(t.get("v", 0)) for t in recent if isinstance(t, dict))
        older_vol = sum(int(t.get("v", 0)) for t in older if isinstance(t, dict))
        
        if older_vol == 0:
            return 0.0
        
        vol_ratio = recent_vol / older_vol
        
        # Volume spike with price direction
        idx = self.market_data.indices.get(instrument)
        if idx and idx.change > 0 and vol_ratio > multiplier:
            return 40  # Bullish volume spike
        elif idx and idx.change < 0 and vol_ratio > multiplier:
            return -40  # Bearish volume spike
        
        return 0.0

    def _analyze_smart_flow(self, instrument: str) -> float:
        """Analyze smart money flow."""
        flow = self.market_data.get_smart_money_flow(instrument)
        return flow.get("score", 0)

    def _build_reason(self, factors: Dict, signal_type: SignalType) -> str:
        """Build human-readable reason for signal."""
        direction = "BULLISH" if signal_type == SignalType.BUY_CE else "BEARISH"
        
        strong_factors = []
        for name, score in factors.items():
            if name == "composite":
                continue
            if abs(score) > 30:
                factor_dir = "bullish" if score > 0 else "bearish"
                strong_factors.append(f"{name}({factor_dir}:{score:.0f})")
        
        return f"{direction} | Composite: {factors['composite']:.1f} | Factors: {', '.join(strong_factors)}"



    # =========================================================================
    # EXECUTION & LIFECYCLE
    # =========================================================================

    def start(self) -> None:
        """Start the strategy engine."""
        self.state.active = True
        logger.info("Strategy engine started in %s mode", self.state.mode)

    def stop(self) -> None:
        """Stop the strategy engine."""
        self.state.active = False
        logger.info("Strategy engine stopped")

    def on_signal(self, callback) -> None:
        """Register callback for new signals."""
        self._signal_callbacks.append(callback)

    def _notify_signal(self, signal: Signal) -> None:
        """Notify all registered callbacks of new signal."""
        for cb in self._signal_callbacks:
            try:
                cb(signal)
            except Exception as e:
                logger.error("Signal callback error: %s", str(e))

    def get_state(self) -> Dict[str, Any]:
        """Get current strategy state with quality filter stats."""
        return {
            "active": self.state.active,
            "mode": self.state.mode,
            "in_position": self.state.in_position,
            "signals_generated": self.state.signals_generated,
            "signals_blocked": self.signals_blocked,
            "golden_eggs": self.golden_eggs_found,
            "spoiled_eggs_avoided": self.spoiled_eggs_avoided,
            "trades_taken": self.state.trades_taken,
            "filter_efficiency": (
                f"{self.signals_blocked}/{self.state.signals_generated + self.signals_blocked} blocked"
                if (self.state.signals_generated + self.signals_blocked) > 0 else "N/A"
            ),
            "last_signal": self.signal_history[-1].__dict__ if self.signal_history else None,
        }

    def get_analysis_summary(self, instrument: str = "NIFTY") -> Dict[str, Any]:
        """Get current analysis without generating signal (for display)."""
        oi_score = self._analyze_oi(instrument)
        iv_score = self._analyze_iv(instrument)
        trend_score = self._analyze_trend()
        vwap_score = self._analyze_vwap(instrument)
        volume_score = self._analyze_volume(instrument)
        flow_score = self._analyze_smart_flow(instrument)
        
        composite = (
            oi_score * 0.25 + iv_score * 0.10 + trend_score * 0.20 +
            vwap_score * 0.15 + volume_score * 0.15 + flow_score * 0.15
        )
        
        # Determine bias
        if composite > 25:
            bias = "BULLISH"
        elif composite < -25:
            bias = "BEARISH"
        else:
            bias = "NEUTRAL"
        
        return {
            "instrument": instrument,
            "timestamp": datetime.now().isoformat(),
            "bias": bias,
            "composite_score": round(composite, 1),
            "scores": {
                "oi": round(oi_score, 1),
                "iv": round(iv_score, 1),
                "trend": round(trend_score, 1),
                "vwap": round(vwap_score, 1),
                "volume": round(volume_score, 1),
                "smart_flow": round(flow_score, 1),
            },
            "atm_strike": self.market_data.get_atm_strike(instrument),
            "pcr": self.market_data.get_pcr(instrument),
            "institutional": self.market_data.detect_institutional_activity(instrument),
        }
